### PR TITLE
computational algorithms

### PR DESCRIPTION
**Pull request by Lord-Morpheus**
B22333- Tarun Srivastava
solve #6 
contains subfolder with algorithms

### CODE REVIEW

**Comment by metabiswadeep** [comment]
Hey @Lord-Morpheus please checkout CONTRIBUTING.md and modify your PR accordingly by adding the required details.

**Comment by Lord-Morpheus** [comment]
please explain what do I have to correct? Thanks!

**Comment by Lord-Morpheus** [comment]
do i need to keep my file directory as computational_algos/graph/file ?

**Comment by Lord-Morpheus** [comment]
@metabiswadeep  i have changed comment, will this do?

**Comment by metabiswadeep** [comment]
> @metabiswadeep i have changed comment, will this do?

Yes it is OK. However please also restructure your folders in such a way to ensure that the Computational Algorithms folder as is present in the current state of the repo stays as the parent folder within which you add your files.

**Comment by Lord-Morpheus** [comment]
@metabiswadeep please check if the file structure is correct now. tTank you!

**Comment by metabiswadeep** [comment]
@Lord-Morpheus The folder structure is now okay. However please modify your code to let the user provide input and also add cout statements to prompt the user to provide the input.

**Comment by Lord-Morpheus** [comment]
@metabiswadeep updated the code to prompt the user to input values.

**Comment by metabiswadeep** [comment]
@Lord-Morpheus Please adhere to the new folder structure of the repo and make changes accordingly

**Comment by Lord-Morpheus** [comment]
@metabiswadeep I have updated the structure but new folder on repo does not contain subfolders as specified by the issue. should I remove subfolders? Thank you!

**Comment by Lord-Morpheus** [comment]
@metabiswadeep I have corrected the structure for this folder.

**Comment by metabiswadeep** [comment]
@Lord-Morpheus Please consider adding comments or even a brief explanation of the logic behind the Disjoint Set Union (DSU) algorithm for those who may not be familiar with it.

**Comment by Lord-Morpheus** [comment]
@metabiswadeep I have made the necessary corrections in all the files also I have added greedy subfolder in this pr.

**Pull request merged**
