### PR TITLE
Linear regression 2d

### PR DESCRIPTION
**Pull request by Vayun-Goel**
Solves #7 
name : Vayun Goel
Roll No. : B22141

### CODE REVIEW

**Comment by Vayun-Goel** [comment]
Hey there @metabiswadeep @CodingWarrior33 , kindly add the linear regression in 2 dimensions to the codebase!

**Comment by metabiswadeep** [comment]
@Vayun-Goel please add 2d somewhere in the filename to distinguish between 1d and 2d logistic regression files.

**Comment by Vayun-Goel** [comment]
@metabiswadeep is this ok?

**Comment by metabiswadeep** [comment]
Also consider removing the linear regression 3d visualizer file from this PR, as this is present in a seperate PR isn't it?

**Comment by Vayun-Goel** [comment]
@metabiswadeep will this work? i am not very sure

**Comment by metabiswadeep** [comment]
Yes this is fine.

**Pull request merged**
