### PR TITLE
file for application folder #5

### PR DESCRIPTION
**Pull request by Lord-Morpheus**
B22333-Tarun Srivastava
issue #5 
contains few real-life applications of stack data structure on a small scale which can be later expanded for large scale anytime.

### CODE REVIEW

**Comment by Lord-Morpheus** [comment]
@metabiswadeep I have added a new file for the application folder.
it is based on a few simple and easy real-life applications of stack data structure on a small scale which can be later expanded to a large scale anytime.

**Comment by Lord-Morpheus** [comment]
@metabiswadeep please tell if there is any thing to change.

**Comment by metabiswadeep** [comment]
@Lord-Morpheus Why are there deletions of files in your PR? Please ensure only those files are present in this PR which are being added. Nothing should be deleted

**Comment by Lord-Morpheus** [comment]
i have corrected the commits

**Pull request closed without merging**
