### PR TITLE
Skiplist added in folder Linked Data Structure for DSA algorithms

### PR DESCRIPTION
**Pull request by Stormbreakerr20**
B22115 
Luv Sharma
Added new DSA algorithm to computational folder

### CODE REVIEW

**Comment by metabiswadeep** [comment]
@Stormbreakerr20 Please change the subfolder to Linked list from linked data structure.

**Comment by Stormbreakerr20** [comment]
Done, I have updated the name

**Comment by metabiswadeep** [comment]
Please add an underscore instead of a space in the folder names

**Comment by Stormbreakerr20** [comment]
Added the underscores in place of spaces

**Comment by metabiswadeep** [comment]
@Stormbreakerr20  Please resolve conflicts.

**Comment by Stormbreakerr20** [comment]
Resolved

**Comment by metabiswadeep** [comment]
@Stormbreakerr20 Why are there so many files undergoing changes in this PR. Please make the necessary changes to ensure that only the file you added is being shown in the files changed tab.

**Comment by Stormbreakerr20** [comment]
I think I should create a new PR as there is some sort of problem with this when I am trying to revert the changes new files are being modified

**Comment by metabiswadeep** [comment]
Sure

**Pull request closed without merging**
