### PR TITLE
Added code for Insertion sort using doubly linked list

### PR DESCRIPTION
**Pull request by ABHIJEETJHA0102**
issue #6 
Insertion sort using doubly linked list
Abhijeet Kumar Jha
B22149

### CODE REVIEW

**Comment by metabiswadeep** [comment]
@ABHIJEETJHA0102 Please explain in detail what the code does and also mention the time complexity of the code inside the code file as a multi-line comment in the beginning of the file.

**Comment by ABHIJEETJHA0102** [comment]
@metabiswadeep  added the algorithm explanation, time complexity and space complexity.

**Comment by metabiswadeep** [comment]
@ABHIJEETJHA0102 In the display function, please add a check to see if head is NULL before attempting to traverse the list to avoid a null-pointer dereference error.

**Comment by ABHIJEETJHA0102** [comment]
@metabiswadeep Done.

**Pull request merged**
