### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Simran211103**

### CODE REVIEW

**Comment by metabiswadeep** [comment]
@Simran211103 Thanks for taking the time to contribute. We essentially need a .py file even while showing implementation of am ML algo and not an .ipynb file.

**Comment by Simran211103** [comment]
will do it as soon as possible

**Comment by Simran211103** [comment]
Changed to .py please check

**Comment by CodingWarrior33** [comment]
@Simran211103 please add a link to the Netflix csv within the code as a comment.

**Comment by CodingWarrior33** [comment]
@Simran211103 thanks for the changes. Merging Now !!

**Pull request merged**
