### PR TITLE
Create kMeans.py

### PR DESCRIPTION
**Pull request by BipanjitGill**
Issue #7 
Bipanjit Singh
B22156

### CODE REVIEW

**Comment by CodingWarrior33** [comment]
Hi @BipanjitGill , thanks a lot for the contribution!

Please update your name and roll number in the comments, provide links to the CSV files within the code, and delete the corresponding CSV files.

**Comment by BipanjitGill** [comment]
Updated name and roll number. Deleted csv

**Comment by CodingWarrior33** [comment]
@BipanjitGill please add comments in the code.

**Comment by CodingWarrior33** [comment]
@BipanjitGill thanks again for the contribution. Merging Now !!!!

**Pull request merged**
