### PR TITLE
Created Application Folder #5

### PR DESCRIPTION
**Pull request by Stormbreakerr20**
B22115_LuvSharma
issue #5 
created application folder along with DSA and Ml algo folder in it adding 1 Algorithm to each one of them of respective domains

### CODE REVIEW

**Comment by CodingWarrior33** [comment]
@Stormbreakerr20 thanks a lot for taking out some time to contribute to the repository.

However , you seem to have misunderstood the directory structure.

Here is the structure 
1) Computational Algorithms
2) ML algorithms 
3) Applications

1) and 2) are for base algorithms , i.e if you want to create the heapify algorithm , you should create a folder called Heaps in the Computational Algorithms directory , and then create the heapifying.cpp codefile within it. Similar process should be followed for ML Algorithms.

The Applications Folder should contain the visualisation or real world example of the algorithm you created in the Computational Algorithm or the ML Algorithm directory. Hope this helps .....

**Comment by Stormbreakerr20** [comment]
Got it, I will update it

**Comment by Stormbreakerr20** [comment]
I have updated the structure as per the requirements....

**Comment by Stormbreakerr20** [comment]
Are there any changes required?

**Comment by CodingWarrior33** [comment]
@Stormbreakerr20, Thanks Again !! 

Just update with the current version of the repository structure and change the python notebooks to python files. Also mention the links to csv in the code instead of adding the file directly.

**Comment by Stormbreakerr20** [comment]
I have updated the folder structure, have contributed for Heaps only.

**Comment by CodingWarrior33** [comment]
@Stormbreakerr20 looks good. Do contribute further !! Merging now .

**Pull request merged**
