### PR TITLE
Adding linear regression 3d visualizer

### PR DESCRIPTION
**Pull request by Vayun-Goel**
Solves #8 
name : Vayun Goel
Roll No. : B22141

### CODE REVIEW

**Comment by Vayun-Goel** [comment]
Hey @metabiswadeep @CodingWarrior33 ! do check out my 3d Linear regression visualizer

**Comment by Vayun-Goel** [comment]
Hi @metabiswadeep, updated the visualizer file based on the changes made to the linear regression in 2d file, do accept the pr!

**Comment by metabiswadeep** [comment]
@Vayun-Goel Please resolve conflicts

**Comment by Vayun-Goel** [comment]
@metabiswadeep i dont seem to have the access to resolve conflicts..... can you do it from your end? or could you suggest a way?

**Comment by metabiswadeep** [comment]
@Vayun-Goel You need to resolve the conflicts on your local PC and push it to GitHub. It seems that the conflicts are too big to resolve on the GitHub web editor.

**Pull request closed without merging**
