### PR TITLE
Bayesian classifier implemented for multivariable data i.e multiple p…

### PR DESCRIPTION
**Pull request by yashsehgal29**
A Bayesian classifier algorithm for multivariable data is a probabilistic approach to classification tasks. It relies on Bayes' theorem to make predictions about the class or category to which a new data point belongs, taking into consideration multiple variables or attributes. During the training phase, the algorithm learns from a labeled dataset, calculating conditional probabilities of observing specific variable values for each class. In the classification phase, when presented with a new data point, it estimates the probability of it belonging to each possible class based on the observed variables. The class with the highest probability is assigned as the predicted label. One fundamental assumption is that the variables are conditionally independent given the class, although this may not always hold in practice. Despite this simplification, Bayesian classifiers are effective in a wide range of applications, including spam email filtering, sentiment analysis, and medical diagnosis, offering a probabilistic framework for making informed classification decisions.

### CODE REVIEW

**Comment by CodingWarrior33** [comment]
Hi @yashsehgal29 , thanks a lot for the awesome contribution to our repository!!!

- Please add your Name and Roll No. in the comments 
- Please add comments to explain what your code does
- Remove the corresponding CSV files and add them as links within the code

**Comment by yashsehgal29** [comment]
changes have been implemented as per the above  comment the corresponding CSV files are  separate so that one can access them easily please tak that in consideration

**Comment by yashsehgal29** [comment]
Yash Sehgal
B22147

**Comment by CodingWarrior33** [comment]
@yashsehgal29 remove the .csv files and add links to them within code comments.

**Comment by yashsehgal29** [comment]
done

**Comment by CodingWarrior33** [comment]
@yashsehgal29 thanks for contributing. Merging Now !!!

**Pull request merged**
