### PR TITLE
Added Floyds Circle Detection Algorithm for Linked Lists and Created Linked Lists Folder

### PR DESCRIPTION
**Pull request by coderbeta1**
Added Floyds Circle Detection Algorithm for Linked Lists and Created Linked Lists Folder

Achal Jain
B22080

### CODE REVIEW

**Comment by metabiswadeep** [comment]
@coderbeta1 Change your parent folder to Computational_Algorithms and your subfolder to Linked_Lists.

**Comment by coderbeta1** [comment]
Implemented the changes asked

**Comment by metabiswadeep** [comment]
@coderbeta1 Why are you using random values as elements of the linked list and not taking the node values as input from the user?

**Comment by coderbeta1** [comment]
The aim of the code is to detect loops in the linked list, hence what values they hold are not of any significance, what matters is the structure of the linked list . So to make the code more readily usable I just took random values

**Comment by metabiswadeep** [comment]
A sample size of 10 random inputs doesn't help in getting an understanding of the algorithm, does it, as the output will nearly always be acyclic. So, please modify your algorithm either using inputs which helps one visualize both cyclic and acyclic cases or by taking the input of the nodes from the user.

**Comment by coderbeta1** [comment]
@metabiswadeep added function called createLoop to loop back the last element of linked list to node k based on user input.

if k==-1 then no loop is created, else last element is looped to kth node

**Pull request merged**
